import { craftingSteps } from '../src'
import { RecipeTreeWithCraftFlags } from '../src/types'

describe('craftingSteps', () => {
  it('gets the correct crafting steps', () => {
    const tree: RecipeTreeWithCraftFlags = {
      craft: true,
      craftDecisionPrice: 6,
      id: 1,
      totalQuantity: 2,
      usedQuantity: 2,
      output: 2,
      type: 'Recipe',
      quantity: 2,
      min_rating: null,
      buyPriceEach: 1,
      buyPrice: 1,
      decisionPrice: 1,
      craftResultPrice: 1,
      disciplines: [],
      multipleRecipeCount: 1,
      daily_purchase_cap: 0,
      weekly_purchase_cap: 0,
      components: [
        {
          craft: true,
          craftDecisionPrice: 1,
          id: 7,
          totalQuantity: 6,
          usedQuantity: 6,
          quantity: 6,
          type: 'Recipe',
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          output: 1,
          min_rating: 400,
          disciplines: ['Armorsmith'],
          prerequisites: [
            {
              type: 'Recipe',
              id: 123,
            },
          ],
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
          components: [
            {
              craft: false,
              craftDecisionPrice: 1,
              id: 4,
              totalQuantity: 12,
              usedQuantity: 12,
              type: 'Item',
              quantity: 12,
              output: 1,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              disciplines: [],
              prerequisites: [],
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
            },
          ],
        },
        {
          craft: true,
          craftDecisionPrice: 1,
          id: 3,
          totalQuantity: 10,
          usedQuantity: 3,
          output: 1,
          type: 'Recipe',
          quantity: 10,
          min_rating: null,
          disciplines: [],
          buyPrice: 1,
          buyPriceEach: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
          components: [
            {
              craft: true,
              craftDecisionPrice: 1,
              id: 19,
              totalQuantity: 3,
              usedQuantity: 3,
              output: 1,
              type: 'Recipe',
              quantity: 3,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
              components: [
                {
                  craft: true,
                  craftDecisionPrice: 1,
                  id: 7,
                  totalQuantity: 3,
                  usedQuantity: 3,
                  output: 1,
                  type: 'Recipe',
                  quantity: 3,
                  min_rating: null,
                  disciplines: [],
                  buyPrice: 1,
                  buyPriceEach: 1,
                  decisionPrice: 1,
                  craftResultPrice: 1,
                  multipleRecipeCount: 1,
                  daily_purchase_cap: 0,
                  weekly_purchase_cap: 0,
                  components: [
                    {
                      craft: false,
                      craftDecisionPrice: 1,
                      id: 4,
                      totalQuantity: 6,
                      usedQuantity: 6,
                      type: 'Item',
                      quantity: 6,
                      output: 1,
                      min_rating: null,
                      buyPriceEach: 1,
                      buyPrice: 1,
                      decisionPrice: 1,
                      craftResultPrice: 1,
                      disciplines: [],
                      prerequisites: [],
                      multipleRecipeCount: 1,
                      daily_purchase_cap: 0,
                      weekly_purchase_cap: 0,
                    },
                  ],
                  prerequisites: [],
                },
              ],
              prerequisites: [],
            },
          ],
          prerequisites: [],
        },
        {
          craft: false,
          craftDecisionPrice: 1,
          id: 5,
          totalQuantity: 4,
          usedQuantity: 0,
          output: 1,
          type: 'Recipe',
          quantity: 4,
          min_rating: null,
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          disciplines: [],
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
          components: [
            {
              craft: false,
              craftDecisionPrice: 1,
              id: 6,
              totalQuantity: 0,
              usedQuantity: 0,
              type: 'Item',
              quantity: 0,
              output: 1,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              disciplines: [],
              prerequisites: [],
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
            },
          ],
          prerequisites: [],
        },
        {
          craft: true,
          craftDecisionPrice: 1,
          id: 15,
          totalQuantity: 1,
          usedQuantity: 1,
          output: 1,
          type: 'Recipe',
          quantity: 1,
          min_rating: null,
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          disciplines: [],
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
          components: [
            {
              craft: true,
              craftDecisionPrice: 1,
              id: 7,
              totalQuantity: 6,
              usedQuantity: 6,
              output: 1,
              type: 'Recipe',
              quantity: 6,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              disciplines: [],
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
              components: [
                {
                  craft: false,
                  craftDecisionPrice: 1,
                  id: 4,
                  totalQuantity: 12,
                  usedQuantity: 12,
                  type: 'Item',
                  quantity: 12,
                  output: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  craftResultPrice: 1,
                  disciplines: [],
                  prerequisites: [],
                  multipleRecipeCount: 1,
                  daily_purchase_cap: 0,
                  weekly_purchase_cap: 0,
                },
              ],
              prerequisites: [],
            },
          ],
          prerequisites: [],
        },
        {
          craft: true,
          craftDecisionPrice: 1,
          id: 1337,
          totalQuantity: 1,
          usedQuantity: 0,
          output: 1,
          type: 'Recipe',
          quantity: 1,
          min_rating: null,
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          disciplines: [],
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
          components: [
            {
              craft: true,
              craftDecisionPrice: 1,
              id: 42,
              totalQuantity: 6,
              usedQuantity: 6,
              output: 1,
              type: 'Item',
              quantity: 6,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              disciplines: [],
              prerequisites: [],
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
            },
          ],
          prerequisites: [],
        },
        {
          craft: true,
          craftDecisionPrice: 1,
          id: 1,
          totalQuantity: 6,
          usedQuantity: 6,
          output: 1,
          type: 'Currency',
          quantity: 6,
          min_rating: null,
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          disciplines: [],
          prerequisites: [],
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
        },
      ],
      prerequisites: [],
    }

    const usedItemObject = craftingSteps(tree)
    expect(usedItemObject).toMatchSnapshot()
  })

  it('gets the correct crafting steps with mystic clovers', () => {
    const tree: RecipeTreeWithCraftFlags = {
      craft: true,
      craftDecisionPrice: 4,
      id: 1,
      totalQuantity: 2,
      usedQuantity: 2,
      output: 2,
      type: 'Recipe',
      quantity: 2,
      min_rating: null,
      buyPriceEach: 1,
      buyPrice: 1,
      decisionPrice: 1,
      craftResultPrice: 1,
      disciplines: [],
      multipleRecipeCount: 1,
      daily_purchase_cap: 0,
      weekly_purchase_cap: 0,
      components: [
        {
          craft: true,
          craftDecisionPrice: 1,
          id: 7,
          totalQuantity: 6,
          usedQuantity: 6,
          quantity: 6,
          type: 'Recipe',
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          output: 1,
          min_rating: 400,
          disciplines: ['Armorsmith'],
          prerequisites: [
            {
              type: 'Recipe',
              id: 123,
            },
          ],
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
          components: [
            {
              craft: false,
              craftDecisionPrice: 1,
              id: 4,
              totalQuantity: 12,
              usedQuantity: 12,
              type: 'Item',
              quantity: 12,
              output: 1,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              disciplines: [],
              prerequisites: [],
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
            },
          ],
        },
        {
          craft: true,
          craftDecisionPrice: 1,
          id: 3,
          totalQuantity: 10,
          usedQuantity: 3,
          output: 1,
          type: 'Recipe',
          quantity: 10,
          min_rating: null,
          disciplines: [],
          buyPrice: 1,
          buyPriceEach: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
          components: [
            {
              craft: true,
              craftDecisionPrice: 1,
              id: 19,
              totalQuantity: 3,
              usedQuantity: 3,
              output: 1,
              type: 'Recipe',
              quantity: 3,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
              components: [
                {
                  craft: true,
                  craftDecisionPrice: 99210,
                  id: 19675,
                  totalQuantity: 3,
                  usedQuantity: 3,
                  output: 1,
                  type: 'Recipe',
                  quantity: 3,
                  min_rating: null,
                  disciplines: [],
                  buyPrice: 1,
                  buyPriceEach: 1,
                  decisionPrice: 1,
                  craftResultPrice: 1,
                  multipleRecipeCount: 1,
                  daily_purchase_cap: 0,
                  weekly_purchase_cap: 0,
                  components: [
                    {
                      craft: true,
                      craftDecisionPrice: 0,
                      id: 19925,
                      type: 'Recipe',
                      quantity: 1,
                      output: 1,
                      multipleRecipeCount: 1,
                      daily_purchase_cap: 0,
                      weekly_purchase_cap: 0,
                      components: [
                        {
                          craft: false,
                          craftDecisionPrice: false,
                          id: 19,
                          type: 'Currency',
                          quantity: 25,
                          output: 1,
                          totalQuantity: 250,
                          usedQuantity: 250,
                          buyPriceEach: false,
                          buyPrice: false,
                          decisionPrice: false,
                          craftResultPrice: false,
                          min_rating: null,
                          disciplines: [],
                          prerequisites: [],
                          multipleRecipeCount: 1,
                          daily_purchase_cap: 0,
                          weekly_purchase_cap: 0,
                        },
                        {
                          craft: false,
                          craftDecisionPrice: false,
                          id: 2,
                          type: 'Currency',
                          quantity: 1050,
                          output: 1,
                          totalQuantity: 10500,
                          usedQuantity: 10500,
                          buyPriceEach: false,
                          buyPrice: false,
                          decisionPrice: false,
                          craftResultPrice: false,
                          min_rating: null,
                          disciplines: [],
                          prerequisites: [],
                          multipleRecipeCount: 1,
                          daily_purchase_cap: 0,
                          weekly_purchase_cap: 0,
                        },
                      ],
                      prerequisites: [],
                      min_rating: null,
                      disciplines: ['Merchant'],
                      merchant: {
                        name: 'Foo',
                        locations: ['Bar'],
                      },
                      totalQuantity: 10,
                      usedQuantity: 10,
                      buyPriceEach: false,
                      buyPrice: false,
                      decisionPrice: 0,
                      craftResultPrice: 0,
                      craftPrice: 0,
                    },
                    {
                      craft: false,
                      craftDecisionPrice: 85920,
                      id: 19976,
                      type: 'Item',
                      quantity: 1,
                      output: 1,
                      totalQuantity: 10,
                      usedQuantity: 10,
                      buyPriceEach: 8592,
                      buyPrice: 85920,
                      decisionPrice: 85920,
                      craftResultPrice: 85920,
                      min_rating: null,
                      disciplines: [],
                      prerequisites: [],
                      multipleRecipeCount: 1,
                      daily_purchase_cap: 0,
                      weekly_purchase_cap: 0,
                    },
                    {
                      craft: false,
                      craftDecisionPrice: 13290,
                      id: 19721,
                      type: 'Item',
                      quantity: 1,
                      output: 1,
                      totalQuantity: 10,
                      usedQuantity: 10,
                      buyPriceEach: 1329,
                      buyPrice: 13290,
                      decisionPrice: 13290,
                      craftResultPrice: 13290,
                      min_rating: null,
                      disciplines: [],
                      prerequisites: [],
                      multipleRecipeCount: 1,
                      daily_purchase_cap: 0,
                      weekly_purchase_cap: 0,
                    },
                    {
                      craft: true,
                      craftDecisionPrice: 0,
                      id: 20796,
                      type: 'Recipe',
                      quantity: 6,
                      output: 10,
                      multipleRecipeCount: 1,
                      daily_purchase_cap: 0,
                      weekly_purchase_cap: 0,
                      components: [
                        {
                          craft: false,
                          craftDecisionPrice: false,
                          id: 23,
                          type: 'Currency',
                          quantity: 1,
                          output: 1,
                          totalQuantity: 6,
                          usedQuantity: 6,
                          buyPriceEach: false,
                          buyPrice: false,
                          decisionPrice: false,
                          craftResultPrice: false,
                          min_rating: null,
                          disciplines: [],
                          prerequisites: [],
                          multipleRecipeCount: 1,
                          daily_purchase_cap: 0,
                          weekly_purchase_cap: 0,
                        },
                      ],
                      prerequisites: [],
                      min_rating: null,
                      disciplines: ['Merchant'],
                      merchant: {
                        name: 'Foo',
                        locations: ['Bar'],
                      },
                      totalQuantity: 60,
                      usedQuantity: 60,
                      buyPriceEach: false,
                      buyPrice: false,
                      decisionPrice: 0,
                      craftResultPrice: 0,
                      craftPrice: 0,
                    },
                  ],
                  prerequisites: [],
                },
              ],
              prerequisites: [],
            },
          ],
          prerequisites: [],
        },
        {
          craft: false,
          craftDecisionPrice: 1,
          id: 5,
          totalQuantity: 4,
          usedQuantity: 0,
          output: 1,
          type: 'Recipe',
          quantity: 4,
          min_rating: null,
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          disciplines: [],
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
          components: [
            {
              craft: false,
              craftDecisionPrice: 1,
              id: 6,
              totalQuantity: 0,
              usedQuantity: 0,
              type: 'Item',
              quantity: 0,
              output: 1,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              disciplines: [],
              prerequisites: [],
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
            },
          ],
          prerequisites: [],
        },
        {
          craft: true,
          craftDecisionPrice: 1,
          id: 15,
          totalQuantity: 1,
          usedQuantity: 1,
          output: 1,
          type: 'Recipe',
          quantity: 1,
          min_rating: null,
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          disciplines: [],
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
          components: [
            {
              craft: true,
              craftDecisionPrice: 1,
              id: 7,
              totalQuantity: 6,
              usedQuantity: 6,
              output: 1,
              type: 'Recipe',
              quantity: 6,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              disciplines: [],
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
              components: [
                {
                  craft: false,
                  craftDecisionPrice: 1,
                  id: 4,
                  totalQuantity: 12,
                  usedQuantity: 12,
                  type: 'Item',
                  quantity: 12,
                  output: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  craftResultPrice: 1,
                  disciplines: [],
                  prerequisites: [],
                  multipleRecipeCount: 1,
                  daily_purchase_cap: 0,
                  weekly_purchase_cap: 0,
                },
              ],
              prerequisites: [],
            },
          ],
          prerequisites: [],
        },
      ],
      prerequisites: [],
    }

    const usedItemObject = craftingSteps(tree)
    expect(usedItemObject).toMatchSnapshot()
  })

  it('gets the correct crafting steps when merging components', () => {
    const tree: RecipeTreeWithCraftFlags = {
      craft: true,
      craftDecisionPrice: 2,
      id: 1,
      totalQuantity: 1,
      usedQuantity: 1,
      output: 1,
      type: 'Recipe',
      quantity: 1,
      min_rating: null,
      disciplines: [],
      buyPrice: 1,
      buyPriceEach: 1,
      decisionPrice: 1,
      craftResultPrice: 1,
      multipleRecipeCount: 1,
      daily_purchase_cap: 0,
      weekly_purchase_cap: 0,
      components: [
        {
          craft: true,
          craftDecisionPrice: 2,
          id: 2,
          totalQuantity: 1,
          usedQuantity: 1,
          output: 1,
          type: 'Recipe',
          quantity: 1,
          min_rating: null,
          disciplines: [],
          buyPrice: 1,
          buyPriceEach: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
          components: [
            {
              craft: false,
              craftDecisionPrice: 1,
              id: 3,
              totalQuantity: 1,
              usedQuantity: 0,
              output: 1,
              type: 'Recipe',
              quantity: 1,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
              components: [
                {
                  craft: false,
                  craftDecisionPrice: 1,
                  id: 4,
                  totalQuantity: 1,
                  usedQuantity: 1,
                  output: 1,
                  type: 'Item',
                  quantity: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  craftResultPrice: 1,
                  disciplines: [],
                  prerequisites: [],
                  multipleRecipeCount: 1,
                  daily_purchase_cap: 0,
                  weekly_purchase_cap: 0,
                },
              ],
              prerequisites: [],
            },
            {
              craft: true,
              craftDecisionPrice: 1,
              id: 5,
              totalQuantity: 1,
              usedQuantity: 1,
              output: 1,
              type: 'Recipe',
              quantity: 1,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
              components: [
                {
                  craft: false,
                  craftDecisionPrice: 1,
                  id: 6,
                  totalQuantity: 1,
                  usedQuantity: 1,
                  output: 1,
                  type: 'Item',
                  quantity: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  craftResultPrice: 1,
                  disciplines: [],
                  prerequisites: [],
                  multipleRecipeCount: 1,
                  daily_purchase_cap: 0,
                  weekly_purchase_cap: 0,
                },
              ],
              prerequisites: [],
            },
          ],
          prerequisites: [],
        },
        {
          craft: true,
          craftDecisionPrice: 2,
          id: 2,
          totalQuantity: 1,
          usedQuantity: 1,
          output: 1,
          type: 'Recipe',
          quantity: 1,
          min_rating: null,
          disciplines: [],
          buyPrice: 1,
          buyPriceEach: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
          components: [
            {
              craft: true,
              craftDecisionPrice: 1,
              id: 3,
              totalQuantity: 1,
              usedQuantity: 1,
              output: 1,
              type: 'Recipe',
              quantity: 1,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
              components: [
                {
                  craft: false,
                  craftDecisionPrice: 1,
                  id: 4,
                  totalQuantity: 1,
                  usedQuantity: 1,
                  output: 1,
                  type: 'Item',
                  quantity: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  craftResultPrice: 1,
                  disciplines: [],
                  prerequisites: [],
                  multipleRecipeCount: 1,
                  daily_purchase_cap: 0,
                  weekly_purchase_cap: 0,
                },
              ],
              prerequisites: [],
            },
            {
              craft: true,
              craftDecisionPrice: 1,
              id: 5,
              totalQuantity: 1,
              usedQuantity: 1,
              output: 1,
              type: 'Recipe',
              quantity: 1,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
              components: [
                {
                  craft: false,
                  craftDecisionPrice: 1,
                  id: 6,
                  totalQuantity: 1,
                  usedQuantity: 1,
                  output: 1,
                  type: 'Item',
                  quantity: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  craftResultPrice: 1,
                  disciplines: [],
                  prerequisites: [],
                  multipleRecipeCount: 1,
                  daily_purchase_cap: 0,
                  weekly_purchase_cap: 0,
                },
              ],
              prerequisites: [],
            },
          ],
          prerequisites: [],
        },
      ],
      prerequisites: [],
    }

    const usedItemObject = craftingSteps(tree)
    expect(usedItemObject).toMatchSnapshot()
  })

  it('only sorts merchants to top if they only use currencies', () => {
    const tree: RecipeTreeWithCraftFlags = {
      id: 91571,
      type: 'Recipe',
      quantity: 1,
      output: 1,
      components: [
        {
          id: 89271,
          type: 'Recipe',
          quantity: 25,
          output: 1,
          components: [
            {
              id: 89140,
              type: 'Item',
              quantity: 10,
              output: 1,
              totalQuantity: 250,
              usedQuantity: 250,
              buyPriceEach: 77,
              buyPrice: 19250,
              decisionPrice: 19250,
              craftResultPrice: 19250,
              craftDecisionPrice: 19250,
              craft: false,
              min_rating: null,
              disciplines: [],
              prerequisites: [],
              multipleRecipeCount: 1,
              daily_purchase_cap: 0,
              weekly_purchase_cap: 0,
            },
          ],
          prerequisites: [
            {
              type: 'Recipe',
              id: 12915,
            },
          ],
          min_rating: 0,
          disciplines: [
            'Leatherworker',
            'Armorsmith',
            'Tailor',
            'Artificer',
            'Weaponsmith',
            'Scribe',
            'Huntsman',
          ],
          totalQuantity: 25,
          usedQuantity: 25,
          buyPriceEach: 770,
          buyPrice: 19250,
          craftPrice: 19250,
          decisionPrice: 19250,
          craftResultPrice: 19250,
          craftDecisionPrice: 19250,
          craft: true,
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
        },
        {
          id: 2,
          type: 'Currency',
          quantity: 35000,
          output: 1,
          totalQuantity: 35000,
          usedQuantity: 35000,
          buyPriceEach: false,
          buyPrice: false,
          decisionPrice: 35000,
          craftResultPrice: false,
          craftDecisionPrice: 35000,
          craft: false,
          min_rating: null,
          disciplines: [],
          prerequisites: [],
          multipleRecipeCount: 1,
          daily_purchase_cap: 0,
          weekly_purchase_cap: 0,
        },
      ],
      prerequisites: [],
      min_rating: null,
      disciplines: ['Merchant'],
      merchant: {
        name: 'Master Artificers',
        locations: ['Crafting Station'],
      },
      multipleRecipeCount: 3,
      daily_purchase_cap: 0,
      weekly_purchase_cap: 0,
      totalQuantity: 1,
      usedQuantity: 1,
      buyPriceEach: false,
      buyPrice: false,
      craftPrice: 19250,
      decisionPrice: 54250,
      craftResultPrice: 19250,
      craftDecisionPrice: 54250,
      craft: true,
    }

    const usedItemObject = craftingSteps(tree)
    expect(usedItemObject).toMatchSnapshot()
  })
})
