import { craftingSteps } from '../src'
import { RecipeTreeWithCraftFlags } from '../src/types'

describe('craftingSteps', () => {
  it('gets the correct crafting steps', () => {
    const tree: RecipeTreeWithCraftFlags = {
      id: 1,
      craft: true,
      totalQuantity: 2,
      usedQuantity: 2,
      output: 2,
      type: 'Recipe',
      quantity: 2,
      min_rating: null,
      buyPriceEach: 1,
      buyPrice: 1,
      decisionPrice: 1,
      disciplines: [],
      components: [
        {
          id: 7,
          craft: true,
          totalQuantity: 6,
          usedQuantity: 6,
          quantity: 6,
          type: 'Recipe',
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          output: 1,
          min_rating: 400,
          disciplines: ['Armorsmith'],
          recipe_id: 123,
          components: [
            {
              id: 4,
              craft: false,
              totalQuantity: 12,
              usedQuantity: 12,
              type: 'Item',
              quantity: 12,
              output: 1,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              disciplines: [],
            },
          ],
        },
        {
          id: 3,
          craft: true,
          totalQuantity: 10,
          usedQuantity: 3,
          output: 1,
          type: 'Recipe',
          quantity: 10,
          min_rating: null,
          disciplines: [],
          buyPrice: 1,
          buyPriceEach: 1,
          decisionPrice: 1,
          components: [
            {
              id: 19,
              craft: true,
              totalQuantity: 3,
              usedQuantity: 3,
              output: 1,
              type: 'Recipe',
              quantity: 3,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              components: [
                {
                  id: 7,
                  craft: true,
                  totalQuantity: 3,
                  usedQuantity: 3,
                  output: 1,
                  type: 'Recipe',
                  quantity: 3,
                  min_rating: null,
                  disciplines: [],
                  buyPrice: 1,
                  buyPriceEach: 1,
                  decisionPrice: 1,
                  components: [
                    {
                      id: 4,
                      craft: false,
                      totalQuantity: 6,
                      usedQuantity: 6,
                      type: 'Item',
                      quantity: 6,
                      output: 1,
                      min_rating: null,
                      buyPriceEach: 1,
                      buyPrice: 1,
                      decisionPrice: 1,
                      disciplines: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 5,
          craft: false,
          totalQuantity: 4,
          usedQuantity: 0,
          output: 1,
          type: 'Recipe',
          quantity: 4,
          min_rating: null,
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          disciplines: [],
          components: [
            {
              id: 6,
              craft: false,
              totalQuantity: 0,
              usedQuantity: 0,
              type: 'Item',
              quantity: 0,
              output: 1,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              disciplines: [],
            },
          ],
        },
        {
          id: 15,
          craft: true,
          totalQuantity: 1,
          usedQuantity: 1,
          output: 1,
          type: 'Recipe',
          quantity: 1,
          min_rating: null,
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          disciplines: [],
          components: [
            {
              id: 7,
              craft: true,
              totalQuantity: 6,
              usedQuantity: 6,
              output: 1,
              type: 'Recipe',
              quantity: 6,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              disciplines: [],
              components: [
                {
                  id: 4,
                  craft: false,
                  totalQuantity: 12,
                  usedQuantity: 12,
                  type: 'Item',
                  quantity: 12,
                  output: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  disciplines: [],
                },
              ],
            },
          ],
        },
        {
          id: 1337,
          craft: true,
          totalQuantity: 1,
          usedQuantity: 0,
          output: 1,
          type: 'Recipe',
          quantity: 1,
          min_rating: null,
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          disciplines: [],
          components: [
            {
              id: 42,
              craft: true,
              totalQuantity: 6,
              usedQuantity: 6,
              output: 1,
              type: 'Item',
              quantity: 6,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              disciplines: [],
            },
          ],
        },
      ],
    }

    const usedItemObject = craftingSteps(tree)
    expect(usedItemObject).toMatchSnapshot()
  })

  it('gets the correct crafting steps with mystic clovers', () => {
    const tree: RecipeTreeWithCraftFlags = {
      id: 1,
      craft: true,
      totalQuantity: 2,
      usedQuantity: 2,
      output: 2,
      type: 'Recipe',
      quantity: 2,
      min_rating: null,
      buyPriceEach: 1,
      buyPrice: 1,
      decisionPrice: 1,
      disciplines: [],
      components: [
        {
          id: 7,
          craft: true,
          totalQuantity: 6,
          usedQuantity: 6,
          quantity: 6,
          type: 'Recipe',
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          output: 1,
          min_rating: 400,
          disciplines: ['Armorsmith'],
          recipe_id: 123,
          components: [
            {
              id: 4,
              craft: false,
              totalQuantity: 12,
              usedQuantity: 12,
              type: 'Item',
              quantity: 12,
              output: 1,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              disciplines: [],
            },
          ],
        },
        {
          id: 3,
          craft: true,
          totalQuantity: 10,
          usedQuantity: 3,
          output: 1,
          type: 'Recipe',
          quantity: 10,
          min_rating: null,
          disciplines: [],
          buyPrice: 1,
          buyPriceEach: 1,
          decisionPrice: 1,
          components: [
            {
              id: 19,
              craft: true,
              totalQuantity: 3,
              usedQuantity: 3,
              output: 1,
              type: 'Recipe',
              quantity: 3,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              components: [
                {
                  id: 19675,
                  craft: true,
                  totalQuantity: 3,
                  usedQuantity: 3,
                  output: 1,
                  type: 'Recipe',
                  quantity: 3,
                  min_rating: null,
                  disciplines: [],
                  buyPrice: 1,
                  buyPriceEach: 1,
                  decisionPrice: 1,
                  components: [
                    {
                      id: 99999,
                      craft: false,
                      totalQuantity: 6,
                      usedQuantity: 6,
                      type: 'Item',
                      quantity: 6,
                      output: 1,
                      min_rating: null,
                      buyPriceEach: 1,
                      buyPrice: 1,
                      decisionPrice: 1,
                      disciplines: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 5,
          craft: false,
          totalQuantity: 4,
          usedQuantity: 0,
          output: 1,
          type: 'Recipe',
          quantity: 4,
          min_rating: null,
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          disciplines: [],
          components: [
            {
              id: 6,
              craft: false,
              totalQuantity: 0,
              usedQuantity: 0,
              type: 'Item',
              quantity: 0,
              output: 1,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              disciplines: [],
            },
          ],
        },
        {
          id: 15,
          craft: true,
          totalQuantity: 1,
          usedQuantity: 1,
          output: 1,
          type: 'Recipe',
          quantity: 1,
          min_rating: null,
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          disciplines: [],
          components: [
            {
              id: 7,
              craft: true,
              totalQuantity: 6,
              usedQuantity: 6,
              output: 1,
              type: 'Recipe',
              quantity: 6,
              min_rating: null,
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              disciplines: [],
              components: [
                {
                  id: 4,
                  craft: false,
                  totalQuantity: 12,
                  usedQuantity: 12,
                  type: 'Item',
                  quantity: 12,
                  output: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  disciplines: [],
                },
              ],
            },
          ],
        },
      ],
    }

    const usedItemObject = craftingSteps(tree)
    expect(usedItemObject).toMatchSnapshot()
  })

  it('gets the correct crafting steps when merging components', () => {
    const tree: RecipeTreeWithCraftFlags = {
      id: 1,
      craft: true,
      totalQuantity: 1,
      usedQuantity: 1,
      output: 1,
      type: 'Recipe',
      quantity: 1,
      min_rating: null,
      disciplines: [],
      buyPrice: 1,
      buyPriceEach: 1,
      decisionPrice: 1,
      components: [
        {
          id: 2,
          craft: true,
          totalQuantity: 1,
          usedQuantity: 1,
          output: 1,
          type: 'Recipe',
          quantity: 1,
          min_rating: null,
          disciplines: [],
          buyPrice: 1,
          buyPriceEach: 1,
          decisionPrice: 1,
          components: [
            {
              id: 3,
              craft: false,
              totalQuantity: 1,
              usedQuantity: 0,
              output: 1,
              type: 'Recipe',
              quantity: 1,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              components: [
                {
                  id: 4,
                  craft: false,
                  totalQuantity: 1,
                  usedQuantity: 1,
                  output: 1,
                  type: 'Item',
                  quantity: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  disciplines: [],
                },
              ],
            },
            {
              id: 5,
              craft: true,
              totalQuantity: 1,
              usedQuantity: 1,
              output: 1,
              type: 'Recipe',
              quantity: 1,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              components: [
                {
                  id: 6,
                  craft: false,
                  totalQuantity: 1,
                  usedQuantity: 1,
                  output: 1,
                  type: 'Item',
                  quantity: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  disciplines: [],
                },
              ],
            },
          ],
        },
        {
          id: 2,
          craft: true,
          totalQuantity: 1,
          usedQuantity: 1,
          output: 1,
          type: 'Recipe',
          quantity: 1,
          min_rating: null,
          disciplines: [],
          buyPrice: 1,
          buyPriceEach: 1,
          decisionPrice: 1,
          components: [
            {
              id: 3,
              craft: true,
              totalQuantity: 1,
              usedQuantity: 1,
              output: 1,
              type: 'Recipe',
              quantity: 1,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              components: [
                {
                  id: 4,
                  craft: false,
                  totalQuantity: 1,
                  usedQuantity: 1,
                  output: 1,
                  type: 'Item',
                  quantity: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  disciplines: [],
                },
              ],
            },
            {
              id: 5,
              craft: true,
              totalQuantity: 1,
              usedQuantity: 1,
              output: 1,
              type: 'Recipe',
              quantity: 1,
              min_rating: null,
              disciplines: [],
              buyPrice: 1,
              buyPriceEach: 1,
              decisionPrice: 1,
              components: [
                {
                  id: 6,
                  craft: false,
                  totalQuantity: 1,
                  usedQuantity: 1,
                  output: 1,
                  type: 'Item',
                  quantity: 1,
                  min_rating: null,
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  disciplines: [],
                },
              ],
            },
          ],
        },
      ],
    }

    const usedItemObject = craftingSteps(tree)

    expect(usedItemObject).toMatchSnapshot()
  })
})
