import { dailyCooldowns } from '../../src'
import { RecipeTreeWithCraftFlags } from '../../src/types'

describe('helpers > dailyCooldowns', () => {
  it('gets all daily cooldowns from a recipe tree', () => {
    const tree: RecipeTreeWithCraftFlags = {
      craft: true,
      craftDecisionPrice: 5,
      id: 1,
      totalQuantity: 2,
      usedQuantity: 2,
      quantity: 2,
      type: 'Recipe',
      output: 1,
      min_rating: null,
      disciplines: [],
      buyPriceEach: 1,
      buyPrice: 1,
      decisionPrice: 1,
      craftResultPrice: 1,
      multipleRecipeCount: 1,
      components: [
        {
          craft: true,
          craftDecisionPrice: 66700,
          id: 92272,
          totalQuantity: 25,
          usedQuantity: 25,
          quantity: 25,
          type: 'Recipe',
          output: 1,
          min_rating: null,
          disciplines: ['Merchant'],
          buyPriceEach: false,
          buyPrice: false,
          decisionPrice: 66700,
          craftResultPrice: 0,
          prerequisites: [],
          multipleRecipeCount: 2,
          components: [
            {
              craft: false,
              craftDecisionPrice: 66700,
              id: 2,
              totalQuantity: 66700,
              usedQuantity: 66700,
              quantity: 2668,
              type: 'Currency',
              output: 1,
              min_rating: null,
              disciplines: [],
              buyPriceEach: false,
              buyPrice: false,
              decisionPrice: 66700,
              craftResultPrice: false,
              prerequisites: [],
              multipleRecipeCount: 1,
            },
          ],
        },
        {
          craft: false,
          craftDecisionPrice: 1,
          id: 66913,
          totalQuantity: 6,
          usedQuantity: 6,
          quantity: 6,
          type: 'Recipe',
          output: 1,
          min_rating: null,
          disciplines: [],
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          multipleRecipeCount: 1,
          components: [
            {
              craft: false,
              craftDecisionPrice: 1,
              id: 4,
              totalQuantity: 12,
              usedQuantity: 12,
              quantity: 12,
              type: 'Item',
              output: 1,
              min_rating: null,
              disciplines: [],
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              prerequisites: [],
              multipleRecipeCount: 1,
            },
          ],
          prerequisites: [],
        },
        {
          craft: true,
          craftDecisionPrice: 1,
          id: 46740,
          totalQuantity: 10,
          usedQuantity: 3,
          quantity: 10,
          type: 'Recipe',
          output: 1,
          min_rating: null,
          disciplines: [],
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          multipleRecipeCount: 1,
          components: [
            {
              craft: true,
              craftDecisionPrice: 1,
              id: 19,
              totalQuantity: 3,
              usedQuantity: 3,
              quantity: 3,
              type: 'Recipe',
              output: 1,
              min_rating: null,
              disciplines: [],
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              multipleRecipeCount: 1,
              components: [
                {
                  craft: true,
                  craftDecisionPrice: 1,
                  id: 66913,
                  totalQuantity: 3,
                  usedQuantity: 3,
                  quantity: 3,
                  type: 'Recipe',
                  output: 1,
                  min_rating: null,
                  disciplines: [],
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  craftResultPrice: 1,
                  multipleRecipeCount: 1,
                  components: [
                    {
                      craft: false,
                      craftDecisionPrice: 1,
                      id: 4,
                      totalQuantity: 6,
                      usedQuantity: 6,
                      quantity: 6,
                      type: 'Item',
                      output: 1,
                      min_rating: null,
                      disciplines: [],
                      buyPriceEach: 1,
                      buyPrice: 1,
                      decisionPrice: 1,
                      craftResultPrice: 1,
                      prerequisites: [],
                      multipleRecipeCount: 1,
                    },
                    {
                      craft: true,
                      craftDecisionPrice: 66700,
                      id: 92272,
                      totalQuantity: 25,
                      usedQuantity: 25,
                      quantity: 25,
                      type: 'Recipe',
                      output: 1,
                      min_rating: null,
                      disciplines: ['Merchant'],
                      buyPriceEach: false,
                      buyPrice: false,
                      decisionPrice: 66700,
                      craftResultPrice: 0,
                      prerequisites: [],
                      multipleRecipeCount: 2,
                      components: [
                        {
                          craft: false,
                          craftDecisionPrice: 66700,
                          id: 2,
                          totalQuantity: 66700,
                          usedQuantity: 66700,
                          quantity: 2668,
                          type: 'Currency',
                          output: 1,
                          min_rating: null,
                          disciplines: [],
                          buyPriceEach: false,
                          buyPrice: false,
                          decisionPrice: 66700,
                          craftResultPrice: false,
                          prerequisites: [],
                          multipleRecipeCount: 1,
                        },
                      ],
                    },
                  ],
                  prerequisites: [],
                },
              ],
              prerequisites: [],
            },
          ],
          prerequisites: [],
        },
        {
          craft: false,
          craftDecisionPrice: 1,
          id: 5,
          totalQuantity: 4,
          usedQuantity: 0,
          quantity: 4,
          type: 'Recipe',
          output: 1,
          min_rating: null,
          disciplines: [],
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          components: [
            {
              craft: false,
              craftDecisionPrice: 1,
              id: 6,
              totalQuantity: 0,
              usedQuantity: 0,
              quantity: 0,
              type: 'Item',
              output: 1,
              min_rating: null,
              disciplines: [],
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              prerequisites: [],
              multipleRecipeCount: 1,
            },
            {
              craft: false,
              craftDecisionPrice: 0,
              id: 92272,
              totalQuantity: 25,
              usedQuantity: 0,
              quantity: 25,
              type: 'Recipe',
              output: 1,
              min_rating: null,
              disciplines: ['Merchant'],
              buyPriceEach: false,
              buyPrice: false,
              decisionPrice: false,
              craftResultPrice: false,
              prerequisites: [],
              multipleRecipeCount: 2,
              components: [
                {
                  craft: false,
                  craftDecisionPrice: 0,
                  id: 2,
                  totalQuantity: 0,
                  usedQuantity: 0,
                  quantity: 2668,
                  type: 'Currency',
                  output: 1,
                  min_rating: null,
                  disciplines: [],
                  buyPriceEach: false,
                  buyPrice: false,
                  decisionPrice: 0,
                  craftResultPrice: false,
                  prerequisites: [],
                  multipleRecipeCount: 1,
                },
              ],
            },
          ],
          prerequisites: [],
          multipleRecipeCount: 1,
        },
        {
          craft: true,
          craftDecisionPrice: 1,
          id: 66913,
          totalQuantity: 1,
          usedQuantity: 1,
          quantity: 1,
          type: 'Recipe',
          output: 1,
          min_rating: null,
          disciplines: [],
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          multipleRecipeCount: 1,
          components: [
            {
              craft: true,
              craftDecisionPrice: 1,
              id: 7,
              totalQuantity: 6,
              usedQuantity: 6,
              quantity: 6,
              type: 'Recipe',
              output: 1,
              min_rating: null,
              disciplines: [],
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
              craftResultPrice: 1,
              multipleRecipeCount: 1,
              components: [
                {
                  craft: false,
                  craftDecisionPrice: 1,
                  id: 4,
                  totalQuantity: 12,
                  usedQuantity: 12,
                  quantity: 12,
                  type: 'Item',
                  output: 1,
                  min_rating: null,
                  disciplines: [],
                  buyPriceEach: 1,
                  buyPrice: 1,
                  decisionPrice: 1,
                  craftResultPrice: 1,
                  prerequisites: [],
                  multipleRecipeCount: 1,
                },
                {
                  craft: true,
                  craftDecisionPrice: 66700,
                  id: 92272,
                  totalQuantity: 25,
                  usedQuantity: 25,
                  quantity: 25,
                  type: 'Recipe',
                  output: 1,
                  min_rating: null,
                  disciplines: ['Merchant'],
                  buyPriceEach: false,
                  buyPrice: false,
                  decisionPrice: 66700,
                  craftResultPrice: 0,
                  prerequisites: [],
                  multipleRecipeCount: 2,
                  components: [
                    {
                      craft: false,
                      craftDecisionPrice: 66700,
                      id: 2,
                      totalQuantity: 66700,
                      usedQuantity: 66700,
                      quantity: 2750,
                      type: 'Currency',
                      output: 1,
                      min_rating: null,
                      disciplines: [],
                      buyPriceEach: false,
                      buyPrice: false,
                      decisionPrice: 66700,
                      craftResultPrice: false,
                      prerequisites: [],
                      multipleRecipeCount: 1,
                    },
                  ],
                },
              ],
              prerequisites: [],
            },
          ],
          prerequisites: [],
        },
        {
          craft: true,
          craftDecisionPrice: 1,
          id: 46736,
          totalQuantity: 1,
          usedQuantity: 1,
          quantity: 1,
          type: 'Item',
          output: 1,
          min_rating: null,
          disciplines: [],
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          craftResultPrice: 1,
          prerequisites: [],
          multipleRecipeCount: 1,
        },
        {
          craft: false,
          craftDecisionPrice: false,
          id: 1,
          totalQuantity: 1,
          usedQuantity: 1,
          quantity: 1,
          type: 'Currency',
          output: 1,
          min_rating: null,
          disciplines: [],
          buyPriceEach: false,
          buyPrice: false,
          decisionPrice: false,
          craftResultPrice: false,
          prerequisites: [],
          multipleRecipeCount: 1,
        },
      ],
      prerequisites: [],
    }

    expect(dailyCooldowns(tree)).toEqual({
      46740: 3,
      66913: 4,
      92272: 50,
    })
  })
})
