import { recipeItems } from '../../src/helpers/recipeItems'
import { RecipeTreeWithCraftFlags } from '../../src/types'

describe('helpers > recipeItems', () => {
  it('gets all unique item ids of a recipe tree', () => {
    const recipeTree: RecipeTreeWithCraftFlags = {
      id: 1,
      craft: true,
      totalQuantity: 6,
      usedQuantity: 6,
      quantity: 6,
      type: 'Recipe',
      output: 1,
      min_rating: null,
      disciplines: [],
      buyPriceEach: 1,
      buyPrice: 1,
      decisionPrice: 1,
      components: [
        {
          id: 2,
          craft: true,
          totalQuantity: 6,
          usedQuantity: 6,
          quantity: 6,
          type: 'Recipe',
          output: 1,
          min_rating: null,
          disciplines: [],
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          components: [
            {
              id: 3,
              craft: true,
              totalQuantity: 1,
              usedQuantity: 1,
              quantity: 1,
              type: 'Item',
              output: 1,
              min_rating: null,
              disciplines: [],
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
            },
            {
              id: 4,
              craft: true,
              totalQuantity: 1,
              usedQuantity: 1,
              quantity: 1,
              type: 'Item',
              output: 1,
              min_rating: null,
              disciplines: [],
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
            },
          ],
        },
        {
          id: 5,
          craft: true,
          totalQuantity: 1,
          usedQuantity: 1,
          quantity: 1,
          type: 'Item',
          output: 1,
          min_rating: null,
          disciplines: [],
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
        },
        {
          id: 6,
          craft: true,
          totalQuantity: 6,
          usedQuantity: 6,
          quantity: 6,
          type: 'Recipe',
          output: 1,
          min_rating: null,
          disciplines: [],
          buyPriceEach: 1,
          buyPrice: 1,
          decisionPrice: 1,
          components: [
            {
              id: 3,
              craft: true,
              totalQuantity: 1,
              usedQuantity: 1,
              quantity: 1,
              type: 'Item',
              output: 1,
              min_rating: null,
              disciplines: [],
              buyPriceEach: 1,
              buyPrice: 1,
              decisionPrice: 1,
            },
          ],
        },
      ],
    }

    expect(recipeItems(recipeTree)).toEqual([1, 2, 3, 4, 5, 6])
  })
})
